"""Unit tests for the OAuth ``state`` nonce in Schwab login.

The Schwab OAuth flow now generates a fresh ``state`` nonce per
attempt, includes it in the authorisation URL, and rejects the
token exchange unless the redirect URL the user pastes back echoes
the same value byte-for-byte.

This is CSRF defence: without ``state``, an attacker who can plant
a malicious redirect URL on the user's machine (e.g. by mailing
them a "here's the link to paste" message) could trick the user
into exchanging an attacker-issued auth code for tokens.

We test the building blocks rather than the full ``main()`` driver:

* :func:`build_authorize_url` includes the state nonce.
* :func:`extract_state` parses it back out of the redirect URL.
* :func:`extract_state` returns ``None`` when the state is absent.

We also verify that the nonces generated by :mod:`secrets` are
unique across calls (regression catch for "someone replaced
:func:`secrets.token_urlsafe` with a constant").
"""
from __future__ import annotations

import secrets
import urllib.parse

import pytest

from tradinglab.data import schwab_login


def test_build_authorize_url_includes_state_when_provided() -> None:
    url = schwab_login.build_authorize_url(
        "APP_KEY",
        "https://127.0.0.1",
        state="NONCE_VALUE_123",
    )
    qs = urllib.parse.urlparse(url).query
    params = urllib.parse.parse_qs(qs)
    assert params.get("state") == ["NONCE_VALUE_123"]


def test_build_authorize_url_omits_state_when_none() -> None:
    """Backward-compat: state is optional in the helper signature."""
    url = schwab_login.build_authorize_url("APP_KEY", "https://127.0.0.1")
    qs = urllib.parse.urlparse(url).query
    params = urllib.parse.parse_qs(qs)
    assert "state" not in params


def test_extract_state_returns_nonce_when_present() -> None:
    url = "https://127.0.0.1/?code=AUTH_CODE&state=NONCE_VALUE_123"
    assert schwab_login.extract_state(url) == "NONCE_VALUE_123"


def test_extract_state_returns_none_when_absent() -> None:
    url = "https://127.0.0.1/?code=AUTH_CODE"
    assert schwab_login.extract_state(url) is None


def test_extract_state_returns_none_for_malformed_url() -> None:
    assert schwab_login.extract_state("not a url at all") is None


def test_extract_code_still_works_when_state_is_present() -> None:
    url = "https://127.0.0.1/?code=AUTH_CODE&state=NONCE"
    assert schwab_login.extract_code(url) == "AUTH_CODE"


def test_secrets_token_urlsafe_is_unique_across_calls() -> None:
    """Sanity check: the nonce source must not be a constant.

    24-byte nonces have ~192 bits of entropy; even 1,000 calls
    should never collide.
    """
    nonces = {secrets.token_urlsafe(24) for _ in range(1000)}
    assert len(nonces) == 1000, "secrets.token_urlsafe must produce unique nonces"


def test_malformed_redirect_has_safe_error():
    url = "https://[broken-secret?code=secret"
    assert schwab_login.extract_state(url) is None
    with pytest.raises(ValueError, match="Invalid redirected URL") as exc:
        schwab_login.extract_code(url)
    assert "secret" not in str(exc.value)


@pytest.mark.parametrize("failure", ["http", "save"])
def test_cli_surfaces_safe_exchange_and_persistence_errors(monkeypatch, capsys, failure):
    from types import SimpleNamespace
    from urllib.error import HTTPError

    from tradinglab.data.credentials import SchwabCredentials
    from tradinglab.data.schwab_auth import TokenCacheError

    creds = SchwabCredentials(app_key="APP_KEY", app_secret="SECRET")
    monkeypatch.setattr(schwab_login, "get_credentials", lambda: SimpleNamespace(schwab=creds))
    monkeypatch.setattr(schwab_login.secrets, "token_urlsafe", lambda n: "NONCE")

    def exchange(*args):
        if failure == "http":
            raise HTTPError("SECRET_URL", 403, "SECRET", {}, None)
        return {"access_token": "AT", "refresh_token": "RT"}

    def save(*args, **kwargs):
        raise TokenCacheError("SECRET persistence context")

    monkeypatch.setattr(schwab_login, "exchange_code_for_tokens", exchange)
    monkeypatch.setattr(schwab_login, "save_token_cache", save)
    assert schwab_login.main(["--redirect-url", "https://127.0.0.1/?state=NONCE&code=CODE"]) == 1
    error = capsys.readouterr().err
    assert "SECRET" not in error
    assert "403" in error if failure == "http" else "token cache" in error
