"""Per-feature smoke subset: sandbox replay engine + persistence + watermark."""
from __future__ import annotations

import pytest

from tests.smoke.test_smoke_full import (
    check_b5_sandbox_save_load,
    check_b6_sandbox_auto_cycle,
    check_b7_sandbox_multitf_context,
    check_b8_sandbox_dialog_lazy_fetch,
    check_b9_toolbar_ticker_labels,
    check_b10_sandbox_multi_interval,
    check_b11_sandbox_full_session_xlim,
    check_b12_sandbox_compare_per_tick_refresh,
    check_b13_sandbox_clock_tz_alignment,
    check_b14_sandbox_visible_list_identity_stable,
    check_b15_sandbox_master_clock_frozen,
    check_b16_sandbox_lookback_boundary_exact,
    check_b17_sandbox_memento_full_restore,
    check_b18_sandbox_reentrancy_guards,
    check_b19_sandbox_end_of_session_boundary,
    check_b20_sandbox_session_restart_state_cleanup,
    check_b21_sandbox_right_arrow_entry_suppression,
    check_b22_sandbox_compare_mid_session_toggle_and_swap,
    check_b23_sandbox_invalidate_focused_panels_contract,
    check_b24_sandbox_watermark_tracks_focus,
    check_b25_sandbox_blind_random_seed,
    check_b26_sandbox_compare_does_not_pan_primary,
    check_b29_aggregation_matches_recompute,
    check_b30_ticker_switching_mid_session,
    check_b31_register_ticker_idempotency_and_rejection,
    check_b32_save_load_mid_session_roundtrip,
    check_b33_engine_determinism,
    check_b34_set_display_interval_state_machine,
    check_b36_lookback_trading_days_not_calendar,
    check_b37_sandbox_compare_survives_focus_swap,
    check_b38_sandbox_compare_change_routing,
    check_b40_sandbox_watchlist_uses_replay_clock,
    check_f0_backtest_kernel,
    check_f1_session_reproducibility,
    check_g0_sandbox_replay_integration,
    check_g1_sandbox_phase1c,
    check_g2_sandbox_open_universe,
)

_CHECKS = [
    check_g0_sandbox_replay_integration,
    check_g1_sandbox_phase1c,
    check_g2_sandbox_open_universe,
    check_b5_sandbox_save_load,
    check_b6_sandbox_auto_cycle,
    check_b7_sandbox_multitf_context,
    check_b8_sandbox_dialog_lazy_fetch,
    check_b9_toolbar_ticker_labels,
    check_b10_sandbox_multi_interval,
    check_b11_sandbox_full_session_xlim,
    check_b12_sandbox_compare_per_tick_refresh,
    check_b13_sandbox_clock_tz_alignment,
    check_b14_sandbox_visible_list_identity_stable,
    check_b15_sandbox_master_clock_frozen,
    check_b16_sandbox_lookback_boundary_exact,
    check_b17_sandbox_memento_full_restore,
    check_b18_sandbox_reentrancy_guards,
    check_b19_sandbox_end_of_session_boundary,
    check_b20_sandbox_session_restart_state_cleanup,
    check_b21_sandbox_right_arrow_entry_suppression,
    check_b22_sandbox_compare_mid_session_toggle_and_swap,
    check_b23_sandbox_invalidate_focused_panels_contract,
    check_b24_sandbox_watermark_tracks_focus,
    check_b25_sandbox_blind_random_seed,
    check_b26_sandbox_compare_does_not_pan_primary,
    check_b29_aggregation_matches_recompute,
    check_b30_ticker_switching_mid_session,
    check_b31_register_ticker_idempotency_and_rejection,
    check_b32_save_load_mid_session_roundtrip,
    check_b33_engine_determinism,
    check_b34_set_display_interval_state_machine,
    check_b36_lookback_trading_days_not_calendar,
    check_b37_sandbox_compare_survives_focus_swap,
    check_b38_sandbox_compare_change_routing,
    check_b40_sandbox_watchlist_uses_replay_clock,
    check_f0_backtest_kernel,
    check_f1_session_reproducibility,
]


@pytest.mark.parametrize("check", _CHECKS, ids=lambda c: c.__name__)
def test_sandbox(app, check) -> None:
    check(app)
