"""Frozen-dataclass model for a single chart drawing (Feature C).

v1 supports horizontal price lines only. The ``kind`` field is
nonetheless typed as a string (not an Enum) so a future "trend"
or "rect" addition is purely additive on the persistence layer
without needing a schema migration.

The ``extra`` mapping is the forward-compat seam: a v2 trend-line
will store its anchor list in ``extra["anchors"]`` rather than
appending positional fields to the dataclass (positional fields
are awkward to round-trip through versions).
"""
from __future__ import annotations

import datetime as _dt
import math
import uuid
from collections.abc import Iterable
from dataclasses import dataclass, field
from dataclasses import replace as _dc_replace
from typing import Any

DEFAULT_COLOR = "#2962ff"
"""TradingView's signature blue.

Chosen as the fixed default because it reads well on both light
and dark themes and matches what traders coming from TV expect.
Per-line color is fully editable via the dialog; the session
caches the last-used color so a burst of red lines all default
to red.
"""

DEFAULT_WIDTH = 1.0
"""Trader's preference (vs SWE's 1.5): 1.0 keeps lines crisp on
busy charts and feels "anchored" rather than "decorative"."""

MAX_WIDTH = 10.0
"""Upper bound on the matplotlib linewidth a drawing may carry.

The dialog slider caps user input at 5.0 (see
``gui/drawing_dialog.py``). This bound is the **load-path** guard
against hand-edited or corrupted ``drawings.json`` smuggling in a
50-point line that obscures half the chart. The cap leaves
headroom for callers that legitimately want a chunky line and
still keeps matplotlib's renderer responsive. Audit
``drawing-width-upper-bound``.
"""

DEFAULT_STYLE = "solid"

DRAWING_KIND_HLINE = "hline"
ALLOWED_KINDS = frozenset({DRAWING_KIND_HLINE})

# Allowed values for the user-facing ``style`` field. Mapped to
# matplotlib linestyle strings in ``render._LINESTYLE_MAP``; kept
# here too so the dialog can validate user input without importing
# the render module.
#
# ``dashdot`` was added after the polish-review audit
# ``drawing-style-options`` found that at the slider's previous
# floor of 0.5pt, dashed and dotted are visually indistinguishable;
# dashdot has a markedly different cadence (``-.-.``) so users
# always have at least one obviously-distinct alternative to solid.
VALID_STYLES = frozenset({"solid", "dashed", "dotted", "dashdot"})


@dataclass(frozen=True)
class Drawing:
    """A single user-placed chart drawing.

    Immutable so it can be safely passed across the event bus,
    rendered into different axes, and cached in dicts without
    accidental mutation. Updates flow through
    :meth:`DrawingStore.update` which constructs a fresh instance
    via :meth:`replace`.

    Fields
    ------
    kind
        v1 only ``"hline"``. Future: ``"trend"`` / ``"rect"`` etc.
    id
        UUIDv4 hex (no dashes). Generated by
        :func:`make_hline_drawing` when absent.
    ticker
        Canonical-key normalized via :func:`normalize_ticker`. The
        store rebuckets drawings whose ``ticker`` field disagrees
        with the bucket key, so callers can be lax.
    price
        Y-axis value in chart units (dollars on a price chart).
        Allowed to carry sub-tick precision; the placement helper
        snaps to $0.01 but the dialog accepts arbitrary floats.
    color
        ``#RRGGBB`` hex. Empty / falsy values fall back to
        :data:`DEFAULT_COLOR` when constructed via
        :func:`make_hline_drawing`.
    width
        Stroke width in points (matplotlib ``linewidth``). Clamped
        to a positive value; the dialog presents a 0.5-step slider
        0.5–5.0.
    style
        One of :data:`VALID_STYLES`. Invalid strings default to
        ``"solid"``.
    label
        Optional free-text label rendered next to the line (e.g.
        "stop", "TP1"). Empty by default; users who don't want
        labels never see them.
    created_at
        ISO-8601 UTC timestamp, second precision. Used for
        debugging and tie-breaking ordering when sorting.
    extra
        Forward-compat field. Empty dict for v1 hlines. A future
        ``kind="trend"`` will use ``extra["anchors"]`` rather than
        introducing positional fields that would break old reads.
    """

    kind: str
    id: str
    ticker: str
    price: float
    color: str
    width: float
    style: str
    label: str = ""
    created_at: str = ""
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """JSON-serialisable dict for :func:`store.write_drawings`."""
        return {
            "kind": self.kind,
            "id": self.id,
            "ticker": self.ticker,
            "price": float(self.price),
            "color": self.color,
            "width": float(self.width),
            "style": self.style,
            "label": self.label,
            "created_at": self.created_at,
            "extra": dict(self.extra),
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> Drawing:
        """Reverse of :meth:`to_dict`.

        Tolerant of missing keys — applies defaults so a
        hand-edited file with sparse entries still loads. Invalid
        ``style`` / ``width`` values are coerced via the same
        helpers used by :func:`make_hline_drawing`.
        """
        return cls(
            kind=str(payload.get("kind", "") or ""),
            id=_coerce_id(payload.get("id")),
            ticker=normalize_ticker(payload.get("ticker", "")),
            price=_coerce_price(payload.get("price")),
            color=_coerce_color(payload.get("color"), fallback=DEFAULT_COLOR),
            width=_coerce_width(payload.get("width")),
            style=_coerce_style(payload.get("style")),
            label=str(payload.get("label", "") or ""),
            created_at=str(payload.get("created_at", "") or ""),
            extra=dict(payload.get("extra", {}) or {}),
        )

    def replace(self, **changes: Any) -> Drawing:
        """Return a copy with ``changes`` applied.

        Keys not on the dataclass are silently dropped so callers
        can pass through editor-form values (including stale form
        keys) without worrying about typos. ``ticker``, ``style``,
        ``width``, and ``price`` are re-coerced so the invariants
        survive: ticker is uppercased, style is clamped to the
        valid set, width is clamped to positive, price is floated.
        Empty ``color`` strings fall back to the current value
        (the dialog uses an empty string to mean "no change").
        """
        valid = set(self.__dataclass_fields__.keys())
        kept: dict[str, Any] = {k: v for k, v in changes.items() if k in valid}
        if "ticker" in kept:
            kept["ticker"] = normalize_ticker(kept["ticker"])
        if "style" in kept:
            kept["style"] = _coerce_style(kept["style"])
        if "width" in kept:
            kept["width"] = _coerce_width(kept["width"])
        if "price" in kept:
            # Route through _coerce_price so NaN/Inf/garbage edits
            # preserve the current value rather than silently
            # corrupting the line (audit ``price-coerce-nan-inf``).
            kept["price"] = _coerce_price(kept["price"], fallback=self.price)
        if "id" in kept:
            # Never allow an empty/whitespace id to replace a valid
            # one — store lookups would collide (audit
            # ``drawing-empty-id``). Preserve current id on bad edit.
            kept["id"] = _coerce_id(kept["id"], fallback=self.id)
        if "color" in kept and not str(kept["color"] or "").strip():
            kept["color"] = self.color
        elif "color" in kept:
            # Lowercase-normalize incoming hex so the in-memory copy
            # always satisfies ``color == color.lower()``. Empty edits
            # fall through to the preserve-current branch above.
            # Audit ``color-hex-case``.
            kept["color"] = _coerce_color(kept["color"], fallback=self.color)
        return _dc_replace(self, **kept)


def normalize_ticker(s: Any) -> str:
    """Canonical-key form: ``" amd ".strip().upper()`` → ``"AMD"``.

    Mirrors the pattern used by
    ``ChartApp._install_sandbox_primary_series`` so
    :data:`ChartApp._confirmed_primary_ticker` always matches a
    store key directly. ``None`` collapses to ``""`` so callers
    don't have to guard.
    """
    if s is None:
        return ""
    return str(s).strip().upper()


def _coerce_price(value: Any, *, fallback: float = 0.0) -> float:
    """Convert ``value`` to a finite float, falling back on failure.

    Rejects ``NaN`` and ``±Infinity`` — neither has a meaningful
    pixel position on a price chart and matplotlib would either
    silently drop the line or warn-spam on every redraw. A
    non-numeric value, NaN, or Infinity all collapse to
    ``fallback`` (default ``0.0``). Callers in mutation paths
    (e.g. :meth:`Drawing.replace`) pass the current price as
    ``fallback`` so an invalid edit preserves the old value
    rather than zeroing the line. Regression: audit
    ``price-coerce-nan-inf`` (fixed 2026-05).
    """
    try:
        f = float(value)
    except (TypeError, ValueError):
        return fallback
    if math.isnan(f) or math.isinf(f):
        return fallback
    return f


def _coerce_width(value: Any) -> float:
    """Clamp to ``(0, MAX_WIDTH]``, fall back to :data:`DEFAULT_WIDTH`.

    Rejects ``NaN`` / ``±Infinity`` (which would silently survive
    a naive ``v <= 0`` guard) and clamps over-large widths to
    :data:`MAX_WIDTH`. A hand-edited drawing with ``"width": 50``
    would render as a 50-point bar that fills the screen; the
    clamp keeps the chart navigable. Audit
    ``drawing-width-upper-bound``.
    """
    try:
        v = float(value)
    except (TypeError, ValueError):
        return DEFAULT_WIDTH
    if math.isnan(v) or math.isinf(v):
        return DEFAULT_WIDTH
    if v <= 0:
        return DEFAULT_WIDTH
    if v > MAX_WIDTH:
        return MAX_WIDTH
    return v


def _coerce_style(value: Any) -> str:
    """Clamp to a recognised style string."""
    s = str(value or "").strip().lower()
    if s in VALID_STYLES:
        return s
    return DEFAULT_STYLE


def _coerce_color(value: Any, *, fallback: str = DEFAULT_COLOR) -> str:
    """Normalize ``#RRGGBB`` / ``#RGB`` hex strings to lowercase.

    The codebase convention is lowercase hex literals (see
    ``test_hex_case_constants.py``). The dialog's ``_choose_color``
    already lowercases user picks at the UI boundary, but on-disk
    ``drawings.json`` files predating that fix — or any hand-edit /
    third-party tool that produced uppercase — round-tripped through
    ``from_dict`` unchanged, leaving a mix of cases in the in-memory
    store. That makes equality checks (``d.color == DEFAULT_COLOR``)
    flaky and breaks the assumption baked into the
    ``hex-case-constants`` audit that the *whole* pipeline is
    lowercase.

    Behaviour:
    - ``None`` / empty / whitespace-only → ``fallback`` (lowercased).
    - Valid ``#RGB`` or ``#RRGGBB`` hex → lowercased copy.
    - Anything else (named colors, ``rgb(...)``, malformed hex) is
      returned stripped + lowercased so matplotlib's named-color
      table (which is case-insensitive) still matches, and so any
      future tightening can rely on ``color == color.lower()``.

    Audit ``color-hex-case``.
    """
    s = str(value or "").strip()
    if not s:
        return str(fallback or DEFAULT_COLOR).lower()
    return s.lower()


def _coerce_id(value: Any, *, fallback: str = "") -> str:
    """Return a non-empty drawing id.

    Strips whitespace from ``value``; if the result is empty,
    returns ``fallback`` when truthy, otherwise generates a new
    UUIDv4 hex. Used by the factory, ``from_dict`` and
    ``replace`` to guarantee no drawing escapes with id ``""`` —
    which would collide on every ``DrawingStore.get`` / ``update``
    / ``remove`` lookup (audit ``drawing-empty-id``).
    """
    s = str(value or "").strip()
    if s:
        return s
    if fallback:
        return fallback
    return uuid.uuid4().hex


def find_nearest_ohlc_snap(
    target_y_px: float,
    candidate_prices_px: Iterable[tuple[float, float]],
    *,
    threshold_px: float = 8.0,
) -> float | None:
    """Return the price (in DATA coords) of the OHLC candidate
    closest to ``target_y_px`` within ``threshold_px`` pixels, or
    ``None`` if nothing qualifies.

    The opt-in "snap to nearest OHLC wick within X pixels"
    feature (Settings → "Snap Alt+H to nearest OHLC") needs to
    consider every visible candle's open/high/low/close and pick
    the one whose pixel-y is closest to where the cursor was
    when ``Alt+H`` fired. Doing the work in pixel space (not data
    space) keeps the snap behaviour identical across a $5 penny
    stock and a $1000 mega-cap — both feel like an 8-pixel snap.

    ``candidate_prices_px`` is an iterable of ``(price_data,
    price_y_px)`` pairs. The caller (``_on_alt_h_placement``)
    owns the coordinate transform so the helper stays pure —
    trivially testable without a real matplotlib axes.

    Tie-breaker: first match wins on tie, which is stable for
    most cases (a candle whose high equals the next bar's open
    sits at the same pixel and either is a fine snap target).

    NaN / non-finite candidate prices are skipped silently so a
    gap-bar (which carries NaN OHLC sentinels in our pipeline)
    can't poison the snap.

    Audit ``drawings-snap-extended``.
    """
    if not math.isfinite(target_y_px) or not math.isfinite(threshold_px):
        return None
    if threshold_px <= 0:
        return None
    best_price: float | None = None
    best_dist: float = math.inf
    for price_data, price_px in candidate_prices_px:
        try:
            p_data = float(price_data)
            p_px = float(price_px)
        except (TypeError, ValueError):
            continue
        if not (math.isfinite(p_data) and math.isfinite(p_px)):
            continue
        dist = abs(p_px - target_y_px)
        if dist > threshold_px:
            continue
        if dist < best_dist:
            best_dist = dist
            best_price = p_data
    return best_price


def snap_price_to_grid(price: float, *, visible_range: float | None = None) -> float:
    """Snap ``price`` to a sensible per-instrument grid.

    The fixed ``round(y, 2)`` behaviour of the v1 Alt+H placement
    is hostile to crypto, forex, and futures: a 1.0852 EUR/USD
    chart snaps every line to 1.09, destroying a 4-decimal
    instrument's resolution. This helper picks a grid spacing
    that adapts to the price magnitude (when ``visible_range`` is
    unknown) or to the visible price scale of the axes (when
    ``visible_range`` is provided), so a stock chart still snaps
    to cents, a forex pair snaps to pipettes, and a low-price
    crypto keeps its significant digits.

    Algorithm:

    1. If ``visible_range`` is a finite positive number, pick the
       grid as the largest power-of-10 not exceeding
       ``visible_range / 2000`` (≈0.05% of the visible window —
       fine enough that the snap is invisible at typical zoom
       levels, coarse enough that the user feels the snap when
       hovering precisely). This is the axes-aware path the
       chart-canvas callers use.
    2. Otherwise (axes-aware fallback unavailable) pick by
       magnitude: prices >= $1 snap to $0.01 (the long-standing
       behaviour for the bulk of US equities); sub-dollar prices
       snap to roughly four significant figures via
       ``10**(floor(log10(abs(price))) - 3)``. Clamps at
       ``10**-10`` so a near-zero price can't blow up to a
       sub-IEEE-754-precision grid.

    Non-finite (NaN/Inf) inputs and zero return unchanged so
    upstream coerce-helpers can still reject them. Negative
    prices snap with the same magnitude-based rule applied to
    their absolute value.

    Audit ``drawings-snap-instrument``.
    """
    if not math.isfinite(price):
        return price
    if price == 0.0:
        return 0.0

    if visible_range is not None and math.isfinite(visible_range) and visible_range > 0:
        target = visible_range / 2000.0
        if target > 0:
            grid = 10.0 ** math.floor(math.log10(target))
            return _round_to_grid(price, grid)

    abs_p = abs(price)
    if abs_p >= 1.0:
        return round(price, 2)
    decade = math.floor(math.log10(abs_p))
    ndigits = max(2, min(-decade + 3, 10))
    return round(price, ndigits)


def _round_to_grid(value: float, grid: float) -> float:
    """Round ``value`` to the nearest multiple of ``grid``.

    Implemented as ``round(value / grid) * grid`` followed by a
    second ``round`` at the grid's decimal-place precision so
    the binary-representation noise of e.g. ``0.1 * 17`` doesn't
    leak into the persisted price (which is stored as a regular
    Python float). Audit ``drawings-snap-instrument``.
    """
    if grid <= 0 or not math.isfinite(grid):
        return value
    snapped = round(value / grid) * grid
    decade = math.floor(math.log10(grid)) if grid > 0 else 0
    if decade < 0:
        return round(snapped, -decade)
    return snapped


def make_hline_drawing(
    ticker: str,
    price: float,
    *,
    color: str = DEFAULT_COLOR,
    width: float = DEFAULT_WIDTH,
    style: str = DEFAULT_STYLE,
    label: str = "",
    drawing_id: str = "",
    created_at: str = "",
) -> Drawing:
    """Factory for a fresh horizontal-line drawing.

    Generates a UUIDv4 hex id when ``drawing_id`` is empty and an
    ISO-8601 UTC ``created_at`` (second precision) when not
    provided. Invalid style names fall back to
    :data:`DEFAULT_STYLE`; non-positive widths fall back to
    :data:`DEFAULT_WIDTH`. The ticker is normalized via
    :func:`normalize_ticker`.

    Callers should typically snap ``price`` to the chart's tick
    increment (e.g. $0.01) before invocation; the model itself
    accepts arbitrary precision because the dialog allows
    half-penny edits for sub-tick instruments.
    """
    # Coerce ``drawing_id``: strip whitespace, default to a fresh
    # UUIDv4 hex on empty input. Audit ``drawing-empty-id``.
    drawing_id = _coerce_id(drawing_id)
    if not created_at:
        created_at = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0, tzinfo=None).isoformat()
    return Drawing(
        kind=DRAWING_KIND_HLINE,
        id=drawing_id,
        ticker=normalize_ticker(ticker),
        price=_coerce_price(price),
        color=_coerce_color(color, fallback=DEFAULT_COLOR),
        width=_coerce_width(width),
        style=_coerce_style(style),
        label=str(label or ""),
        created_at=created_at,
        extra={},
    )


__all__ = [
    "ALLOWED_KINDS",
    "DEFAULT_COLOR",
    "DEFAULT_STYLE",
    "DEFAULT_WIDTH",
    "DRAWING_KIND_HLINE",
    "Drawing",
    "MAX_WIDTH",
    "VALID_STYLES",
    "make_hline_drawing",
    "normalize_ticker",
    "snap_price_to_grid",
]
