"""Hexagonal honeycomb color palette popup.

A small modal :class:`tkinter.Toplevel` that lets the user pick a
hex color either from a fixed honeycomb of swatches or by clicking
"Custom…" to open the OS color chooser. Returns the chosen color
hex string (e.g. ``"#1f77b4"``) or ``None`` if the user cancels.

Design notes
------------

* **Honeycomb geometry.** Cells are flat-top hexagons drawn on a
  Tk Canvas via :py:meth:`Canvas.create_polygon`. Center cell + two
  rings = 1 + 6 + 12 = 19 swatches. Each ring is generated by walking
  in axial coordinates (q, r) starting at ``(n, 0)`` and stepping
  through six directions ``n`` cells each — the standard hex ring
  algorithm.

* **Color mapping.** Center is white. Ring 1 is the six pure RGB /
  CMY hues at full saturation. Ring 2 alternates "tint" (light) and
  "shade" (dark) variants of those six hues so neighbouring cells
  are perceptually related.

* **Custom… button.** Falls back to :func:`tkinter.colorchooser.askcolor`
  for free hex entry / standard OS picker, so users aren't stuck
  with the 19-swatch palette.

* **Modal via ``wait_window``.** :func:`pick_color` blocks until the
  popup is dismissed and returns the chosen hex (or ``None``). The
  popup grabs focus so background widgets don't take input while
  the picker is open.
"""

from __future__ import annotations

import math
import tkinter as tk
from tkinter import colorchooser, ttk

# 19-swatch honeycomb laid out as: index 0 = center; indices 1-6 =
# ring 1 in CW order starting at axial (1, 0); indices 7-18 = ring 2
# in CW order starting at axial (2, 0).
_HONEYCOMB_COLORS: tuple[str, ...] = (
    # Center
    "#ffffff",
    # Ring 1 — six pure hues at full saturation, anchored at red (E)
    "#e51d1d",  # red
    "#e5a41d",  # orange
    "#a4e51d",  # yellow-green
    "#1de5a4",  # teal
    "#1da4e5",  # blue
    "#a41de5",  # magenta-purple
    # Ring 2 — alternating light tint / dark shade pairs around the
    # outside, ordered CW from axial (2, 0) so each pair sits next
    # to its parent ring-1 hue.
    "#ff8080", "#a60000",      # red pair
    "#ffcc80", "#a66600",      # orange pair
    "#d9ff80", "#5c8000",      # yellow-green pair
    "#80ffcc", "#008055",      # teal pair
    "#80ccff", "#003d80",      # blue pair
    "#cc80ff", "#5c0080",      # purple pair
)

# Six grayscale swatches drawn as a row beneath the honeycomb so the
# user can pick a neutral without leaving the palette.
_GRAYSCALE_COLORS: tuple[str, ...] = (
    "#000000", "#333333", "#666666", "#999999", "#cccccc", "#ffffff",
)

# Hex cell radius (center → vertex), in pixels. 22 keeps the popup
# small while still tappable.
_HEX_RADIUS = 22


def _axial_to_pixel(q: int, r: int, size: float) -> tuple[float, float]:
    """Flat-top axial → pixel.

    See https://www.redblobgames.com/grids/hexagons/#hex-to-pixel —
    flat-top orientation is ``x = 1.5*size*q``, ``y = √3*size*(r + q/2)``.
    """
    x = 1.5 * size * q
    y = math.sqrt(3.0) * size * (r + q / 2.0)
    return x, y


def _ring_axials(n: int) -> list[tuple[int, int]]:
    """Axial coords of the cells that make up ring ``n``.

    ``n == 0`` returns the center; otherwise walks 6n cells CW
    around the ring starting at ``(n, 0)``.
    """
    if n == 0:
        return [(0, 0)]
    # Direction vectors for CW walk starting at the east cell. Each
    # ring step traverses ``n`` cells in a direction before turning.
    # Ordering chosen so the 12 cells of ring 2 are adjacent in pairs.
    dirs = [(-1, +1), (-1, 0), (0, -1), (+1, -1), (+1, 0), (0, +1)]
    cells: list[tuple[int, int]] = []
    q, r = n, 0
    for dq, dr in dirs:
        for _ in range(n):
            cells.append((q, r))
            q += dq
            r += dr
    return cells


def _hex_polygon_points(cx: float, cy: float, size: float) -> list[float]:
    """Return the 12-element flattened (x, y) point list for a flat-top
    hexagon centered at ``(cx, cy)`` with circumradius ``size``."""
    pts: list[float] = []
    for k in range(6):
        ang = math.radians(60.0 * k)
        pts.append(cx + size * math.cos(ang))
        pts.append(cy + size * math.sin(ang))
    return pts


class HexColorPalette(tk.Toplevel):
    """Modal honeycomb color picker.

    Use :func:`pick_color` instead of constructing this class
    directly — it blocks via ``wait_window`` and returns the result.
    """

    def __init__(self, parent: tk.Misc, initial: str = "#888888",
                 title: str = "Pick a color") -> None:
        super().__init__(parent)
        self.title(title)
        self.transient(parent)
        self.resizable(False, False)
        self.result: str | None = None
        self._initial: str = self._normalise(initial)
        # ``_cell_items`` maps (canvas_id, color_hex) so we can
        # re-stroke the highlight when the user moves the cursor and
        # re-stroke the previously selected cell on click.
        self._cell_items: list[tuple[int, str]] = []
        self._build_ui()
        # Geometry persistence — if a position was stored from a prior
        # open, use it; otherwise center on parent (legacy default).
        from .geometry_store import store as _gs_store
        try:
            stored = _gs_store().get_window("dlg.color_palette")
        except Exception:  # noqa: BLE001
            stored = None
        if stored:
            try:
                from .geometry_store import attach_persistent_geometry
                # Use stored geometry's size if any; for this fixed-size
                # dialog, only the position portion really matters.
                attach_persistent_geometry(
                    self, "dlg.color_palette", stored,
                )
            except tk.TclError:
                pass
        else:
            try:
                self.update_idletasks()
                px = parent.winfo_rootx() + parent.winfo_width() // 2
                py = parent.winfo_rooty() + parent.winfo_height() // 2
                self.geometry(f"+{max(0, px - self.winfo_width() // 2)}"
                              f"+{max(0, py - self.winfo_height() // 2)}")
            except tk.TclError:
                pass
            # Wire the save-on-Configure binding so subsequent opens
            # remember the user's preferred screen position.
            try:
                from .geometry_store import attach_persistent_geometry
                # Pass the current (just-applied centered) geometry as
                # the default so restore-on-bind doesn't move us yet.
                current = self.winfo_geometry()
                attach_persistent_geometry(
                    self, "dlg.color_palette", current or "260x260+0+0",
                )
            except tk.TclError:
                pass
        try:
            self.grab_set()
        except tk.TclError:
            pass
        self.protocol("WM_DELETE_WINDOW", self._on_cancel)
        # Match the rest of the modal-dialog inventory: ESC dismisses
        # the picker (no primary commit — selection happens on click).
        try:
            from ._modal_keys import bind_modal_keys
            bind_modal_keys(self, cancel=self._on_cancel, primary=None)
        except tk.TclError:
            pass

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------

    def _build_ui(self) -> None:
        outer = tk.Frame(self, padx=10, pady=10)
        outer.pack(fill="both", expand=True)

        # Honeycomb canvas. Compute total extent from the ring-2
        # bounding box so the canvas fits exactly.
        size = float(_HEX_RADIUS)
        # Axial (2, 0) and (-2, 0) are the east/west extremes; (1, -2)
        # and (-1, +2) and similar give the y extremes. Compute over
        # all cells to be safe.
        all_cells = (_ring_axials(0) + _ring_axials(1) + _ring_axials(2))
        xs: list[float] = []
        ys: list[float] = []
        for q, r in all_cells:
            x, y = _axial_to_pixel(q, r, size)
            xs.append(x)
            ys.append(y)
        margin = size + 4
        cw = int(max(xs) - min(xs) + 2 * margin)
        ch = int(max(ys) - min(ys) + 2 * margin)
        ox = -min(xs) + margin
        oy = -min(ys) + margin

        canvas = tk.Canvas(outer, width=cw, height=ch,
                           highlightthickness=0, bd=0)
        canvas.pack(side="top")
        self._canvas = canvas

        # Render rings in order (center → ring 1 → ring 2) so the
        # color list lines up with the precomputed 19-color table.
        idx = 0
        for n in (0, 1, 2):
            for (q, r) in _ring_axials(n):
                cx, cy = _axial_to_pixel(q, r, size)
                cx += ox
                cy += oy
                color = _HONEYCOMB_COLORS[idx]
                pts = _hex_polygon_points(cx, cy, size - 1.5)
                stroke = "#222222" if color.lower() == self._initial.lower() else "#777777"
                w = 3 if color.lower() == self._initial.lower() else 1
                cid = canvas.create_polygon(
                    *pts, fill=color, outline=stroke, width=w,
                )
                # Bind clicks and hover effects per-cell.
                canvas.tag_bind(
                    cid, "<Button-1>",
                    lambda _e, c=color: self._on_pick(c),
                )
                canvas.tag_bind(
                    cid, "<Enter>",
                    lambda _e, i=cid: canvas.itemconfigure(i, width=2),
                )
                canvas.tag_bind(
                    cid, "<Leave>",
                    lambda _e, i=cid, c=color: canvas.itemconfigure(
                        i, width=(3 if c.lower() == self._initial.lower() else 1),
                    ),
                )
                self._cell_items.append((cid, color))
                idx += 1

        # Grayscale row.
        gs_frame = tk.Frame(outer)
        gs_frame.pack(side="top", pady=(8, 0))
        tk.Label(gs_frame, text="Gray:").pack(side="left", padx=(0, 6))
        for color in _GRAYSCALE_COLORS:
            btn = tk.Frame(
                gs_frame, width=24, height=20,
                bg=color, bd=1, relief="solid",
                cursor="hand2",
            )
            btn.pack_propagate(False)
            btn.pack(side="left", padx=1)
            btn.bind("<Button-1>",
                     lambda _e, c=color: self._on_pick(c))

        # Bottom button row: Custom… + Cancel.
        bar = tk.Frame(outer)
        bar.pack(side="top", fill="x", pady=(10, 0))
        ttk.Button(bar, text="Custom…",
                   command=self._on_custom).pack(side="left")
        ttk.Button(bar, text="Cancel",
                   command=self._on_cancel).pack(side="right")

    # ------------------------------------------------------------------
    # Callbacks
    # ------------------------------------------------------------------

    def _on_pick(self, color: str) -> None:
        self.result = self._normalise(color)
        self._dismiss()

    def _on_custom(self) -> None:
        try:
            res = colorchooser.askcolor(
                color=self._initial, parent=self, title="Pick custom color",
            )
        except tk.TclError:
            res = (None, None)
        if res and res[1]:
            self.result = self._normalise(res[1])
            self._dismiss()

    def _on_cancel(self) -> None:
        self.result = None
        self._dismiss()

    def _dismiss(self) -> None:
        try:
            self.grab_release()
        except tk.TclError:
            pass
        try:
            self.destroy()
        except tk.TclError:
            pass

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalise(color: str) -> str:
        """Normalise to ``"#rrggbb"`` lower-case form when possible."""
        s = (color or "").strip()
        if not s:
            return "#888888"
        if s.startswith("#") and len(s) == 7:
            return "#" + s[1:].lower()
        if s.startswith("#") and len(s) == 4:
            # #rgb → #rrggbb
            r, g, b = s[1], s[2], s[3]
            return ("#" + r + r + g + g + b + b).lower()
        return s


def pick_color(parent: tk.Misc, initial: str = "#888888",
               title: str = "Pick a color") -> str | None:
    """Open the hex color palette modally and return the chosen color.

    Returns ``None`` if the user cancels (Esc / Cancel / WM close).
    Blocks the calling thread via ``wait_window`` — the caller must
    be on the Tk main thread.
    """
    dlg = HexColorPalette(parent, initial=initial, title=title)
    try:
        dlg.wait_window()
    except tk.TclError:
        return None
    return dlg.result
